owner: scaleupventures01
repo: offerpath-upptime
sites:
  - name: Homepage
    url: https://www.offerpath.co
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Get Started
  - name: About
    url: https://www.offerpath.co/about
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Mission
  - name: Calculator
    url: https://www.offerpath.co/calculator
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Calculate
  - name: Cancellation
    url: https://www.offerpath.co/cancellation
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Church Board
    url: https://www.offerpath.co/church-board
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Enterprise
    url: https://www.offerpath.co/enterprise
    __dangerous__body_down_if_text_missing: OfferPath
  - name: FAQ
    url: https://www.offerpath.co/faq
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Frequently Asked
  - name: For Designers
    url: https://www.offerpath.co/for-designers
    __dangerous__body_down_if_text_missing: OfferPath
  - name: For Engineers
    url: https://www.offerpath.co/for-engineers
    __dangerous__body_down_if_text_missing: OfferPath
  - name: For Product Managers
    url: https://www.offerpath.co/for-product-managers
    __dangerous__body_down_if_text_missing: OfferPath
  - name: For Visa Holders
    url: https://www.offerpath.co/for-visa-holders
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Glossary
    url: https://www.offerpath.co/glossary
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Insights
    url: https://www.offerpath.co/insights
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Jobs
    url: https://www.offerpath.co/jobs
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Job
  - name: LinkedIn Optimization
    url: https://www.offerpath.co/linkedin-optimization
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Login
    url: https://www.offerpath.co/login
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Partners
    url: https://www.offerpath.co/partners
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Pricing
    url: https://www.offerpath.co/pricing
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Starter
  - name: Privacy Policy
    url: https://www.offerpath.co/privacy
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Resources
    url: https://www.offerpath.co/resources
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Salary Discovery
    url: https://www.offerpath.co/salary-discovery
    __dangerous__body_down_if_text_missing: OfferPath
  - name: ScaleJobs
    url: https://www.offerpath.co/scalejobs
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Schedule
    url: https://www.offerpath.co/schedule
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Schedule
  - name: Sign Up
    url: https://www.offerpath.co/signup
    __dangerous__body_down_if_text_missing: OfferPath
  - name: Success Stories
    url: https://www.offerpath.co/success-stories
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Stories
  - name: Terms of Service
    url: https://www.offerpath.co/terms
    __dangerous__body_down_if_text_missing: OfferPath
  - name: "Tool: ATS Checker"
    url: https://www.offerpath.co/tools/ats-checker
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Resume
  - name: "Tool: Cover Letter"
    url: https://www.offerpath.co/tools/cover-letter
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Cover Letter
  - name: "Tool: LinkedIn Analyzer"
    url: https://www.offerpath.co/tools/linkedin-analyzer
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: LinkedIn
  - name: "Tool: Salary Calculator"
    url: https://www.offerpath.co/tools/salary
    __dangerous__body_down_if_text_missing: OfferPath
    __dangerous__body_degraded_if_text_missing: Salary
  - name: Payment Verification
    url: https://www.offerpath.co/api/verify-checkout-session
    expectedStatusCodes:
      - 200
      - 400
  - name: Scheduling Service
    url: https://www.offerpath.co/api/scheduling/book-slot
    expectedStatusCodes:
      - 200
      - 400
      - 500
  - name: VA Availability
    url: https://www.offerpath.co/api/va/availability
    expectedStatusCodes:
      - 200
      - 400
      - 401
      - 500
  - name: Checkout Service
    url: https://www.offerpath.co/api/create-checkout-session
    expectedStatusCodes:
      - 405
  - name: Payment Webhooks
    url: https://www.offerpath.co/api/stripe-webhook
    expectedStatusCodes:
      - 405
  - name: Email Service
    url: https://www.offerpath.co/api/send-email
    expectedStatusCodes:
      - 405
  - name: SMS Service
    url: https://www.offerpath.co/api/send-sms
    expectedStatusCodes:
      - 405
  - name: Profile Notifications
    url: https://www.offerpath.co/api/notify-new-profile
    expectedStatusCodes:
      - 405
  - name: CRM Sync
    url: https://www.offerpath.co/api/sync-to-attio
    expectedStatusCodes:
      - 405
  - name: VA Magic Link
    url: https://www.offerpath.co/api/va/send-magic-link
    expectedStatusCodes:
      - 405
  - name: VA Token Verify
    url: https://www.offerpath.co/api/va/verify-token
    expectedStatusCodes:
      - 405
status-website:
  cname: status.offerpath.co
  logoUrl: https://www.offerpath.co/offerpath-logo.jpg
  name: OfferPath Status
  introTitle: "**OfferPath** System Status"
  introMessage: This page shows real-time uptime monitoring for [OfferPath](https://www.offerpath.co). Checks run every 5 minutes.
  theme: light
  navbar:
    - title: OfferPath
      href: https://www.offerpath.co
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: |
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');
    :root { --op-blue: #2563eb; --op-green: #10b981; --op-green-light: #d1fae5; --op-green-bg: #ecfdf5; --op-red: #ef4444; --op-yellow: #f59e0b; --op-g50: #f9fafb; --op-g100: #f3f4f6; --op-g200: #e5e7eb; --op-g300: #d1d5db; --op-g400: #9ca3af; --op-g500: #6b7280; --op-g700: #374151; --op-g800: #1f2937; --op-g900: #111827; }
    @keyframes pulse { 0%,100% { box-shadow: 0 0 0 4px rgba(16,185,129,0.25); } 50% { box-shadow: 0 0 0 8px rgba(16,185,129,0.08); } }
    body { background: var(--op-g50) !important; font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif !important; color: var(--op-g900) !important; -webkit-font-smoothing: antialiased !important; }
    /* Nav */
    nav { background: white !important; border-bottom: 1px solid var(--op-g200) !important; box-shadow: 0 1px 3px rgba(0,0,0,0.04) !important; position: sticky !important; top: 0 !important; z-index: 100 !important; }
    nav .logo img { height: 28px !important; border-radius: 6px !important; }
    nav .logo div { font-weight: 700 !important; font-size: 1.05rem !important; color: var(--op-g900) !important; letter-spacing: -0.01em !important; }
    nav ul { display: flex !important; gap: 1.25rem !important; }
    nav ul a { color: var(--op-g500) !important; font-weight: 500 !important; font-size: 0.875rem !important; }
    nav ul a:hover { color: var(--op-blue) !important; }
    /* Main */
    main.container { max-width: 920px !important; margin: 0 auto !important; padding: 2rem 1.5rem 4rem !important; }
    /* Header */
    main h1 { font-size: 2rem !important; font-weight: 700 !important; color: var(--op-g900) !important; letter-spacing: -0.025em !important; margin-bottom: 0.35rem !important; }
    main .lead { font-size: 0.95rem !important; color: var(--op-g500) !important; margin-bottom: 1.75rem !important; }
    main .lead a { color: var(--op-blue) !important; text-decoration: none !important; }
    /* All Systems Operational banner - hide emoji, show only CSS pulse dot + text */
    main > article.up:not(.link) { background: var(--op-green-bg) !important; border: 1px solid #a7f3d0 !important; border-radius: 12px !important; padding: 1.1rem 1.5rem !important; font-weight: 600 !important; color: #065f46 !important; font-size: 0 !important; margin-bottom: 2rem !important; box-shadow: none !important; display: flex !important; align-items: center !important; gap: 12px !important; }
    main > article.up:not(.link)::before { content: "" !important; display: inline-block !important; width: 12px !important; height: 12px !important; background: var(--op-green) !important; border-radius: 50% !important; flex-shrink: 0 !important; animation: pulse 2s ease-in-out infinite !important; }
    main > article.up:not(.link)::after { content: "All systems are operational" !important; font-size: 1rem !important; font-weight: 600 !important; color: #065f46 !important; }
    /* Sections */
    main > section { background: white !important; border: 1px solid var(--op-g200) !important; border-radius: 12px !important; padding: 1.25rem 1.5rem !important; margin-bottom: 1rem !important; box-shadow: 0 1px 2px rgba(0,0,0,0.04) !important; }
    main > section h2 { font-size: 1.1rem !important; font-weight: 600 !important; color: var(--op-g900) !important; margin-bottom: 0.75rem !important; }
    main > section:empty { display: none !important; }
    /* Live Status wrapper */
    main > div.f { display: flex !important; flex-direction: row !important; align-items: center !important; justify-content: space-between !important; flex-wrap: wrap !important; gap: 0.75rem !important; margin-bottom: 1rem !important; }
    main > div.f > h2 { font-size: 1.1rem !important; font-weight: 600 !important; color: var(--op-g900) !important; margin: 0 !important; }
    /* Time range pills */
    form.f, form.r, form.f.r { display: flex !important; flex-direction: row !important; flex-wrap: wrap !important; align-items: center !important; gap: 6px !important; margin: 0 !important; padding: 0 !important; }
    form input[type="radio"] { position: absolute !important; opacity: 0 !important; width: 0 !important; height: 0 !important; pointer-events: none !important; }
    form label { display: inline-flex !important; align-items: center !important; justify-content: center !important; padding: 5px 14px !important; margin: 0 !important; background: var(--op-g100) !important; border: 1px solid var(--op-g200) !important; border-radius: 6px !important; font-size: 0.8rem !important; font-weight: 500 !important; color: var(--op-g700) !important; cursor: pointer !important; transition: all 0.15s !important; white-space: nowrap !important; }
    form label:hover { background: var(--op-g200) !important; }
    form input[type="radio"]:checked + label { background: var(--op-blue) !important; color: white !important; border-color: var(--op-blue) !important; font-weight: 600 !important; }
    /* Live status section — transparent */
    .live-status, section.live-status { background: transparent !important; border: none !important; box-shadow: none !important; padding: 0 !important; margin: 0 !important; }
    /* Service cards — HORIZONTAL GRID layout, more compact */
    section.live-status article.up, section.live-status article.up.link, section.live-status article.degraded { display: grid !important; grid-template-columns: 1fr auto auto !important; align-items: center !important; gap: 1rem !important; background: white !important; border: 1px solid var(--op-g200) !important; border-radius: 10px !important; padding: 0.65rem 1rem !important; margin-bottom: 0.4rem !important; box-shadow: 0 1px 2px rgba(0,0,0,0.04) !important; transition: all 0.15s !important; position: relative !important; overflow: hidden !important; }
    section.live-status article:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.07) !important; border-color: var(--op-g300) !important; transform: translateY(-1px) !important; }
    /* Status dots on service cards */
    section.live-status article.up h4::before { content: "" !important; display: inline-block !important; width: 8px !important; height: 8px !important; background: var(--op-green) !important; border-radius: 50% !important; margin-right: 10px !important; box-shadow: 0 0 0 3px var(--op-green-light) !important; flex-shrink: 0 !important; }
    section.live-status article.degraded h4::before { content: "" !important; display: inline-block !important; width: 8px !important; height: 8px !important; background: var(--op-yellow) !important; border-radius: 50% !important; margin-right: 10px !important; box-shadow: 0 0 0 3px rgba(245,158,11,0.2) !important; flex-shrink: 0 !important; }
    /* Service name - HIDE DuckDuckGo favicon icons */
    section.live-status article h4 { display: flex !important; align-items: center !important; font-size: 0.9rem !important; font-weight: 600 !important; margin: 0 !important; }
    section.live-status article h4 .icon { display: none !important; }
    section.live-status article h4 a { color: var(--op-g900) !important; text-decoration: none !important; }
    section.live-status article h4 a:hover { color: var(--op-blue) !important; }
    /* Stats in grid — compact inline */
    section.live-status article > div { font-size: 0.8rem !important; color: var(--op-g500) !important; margin: 0 !important; white-space: nowrap !important; line-height: 1 !important; }
    section.live-status article .data { font-weight: 600 !important; color: var(--op-g800) !important; }
    /* Graph background — MORE PROMINENT and LARGER */
    section.live-status article.graph { background-image: var(--background) !important; background-size: 240px 40px !important; background-position: right center !important; background-repeat: no-repeat !important; }
    /* Down incidents */
    article.down { background: #fef2f2 !important; border: 1px solid #fecaca !important; border-radius: 8px !important; padding: 0.85rem 1.1rem !important; margin-bottom: 0.6rem !important; }
    article.down h4 { display: flex !important; align-items: center !important; font-size: 0.9rem !important; font-weight: 600 !important; margin: 0 0 4px 0 !important; }
    article.down h4::before { content: "" !important; display: inline-block !important; width: 8px !important; height: 8px !important; background: var(--op-red) !important; border-radius: 50% !important; margin-right: 8px !important; box-shadow: 0 0 0 3px rgba(239,68,68,0.2) !important; flex-shrink: 0 !important; }
    article.down h4 { color: var(--op-red) !important; }
    article.down-resolved { opacity: 0.85 !important; border-left: 3px solid var(--op-g300) !important; }
    /* Past Incidents section */
    main > section:last-of-type h3 { font-size: 0.85rem !important; color: var(--op-g400) !important; font-weight: 500 !important; margin-bottom: 0.5rem !important; }
    /* Footer */
    footer { margin-top: 3rem !important; padding: 1.5rem 0 !important; text-align: center !important; color: var(--op-g400) !important; font-size: 0.8rem !important; border-top: 1px solid var(--op-g200) !important; }
    footer a { color: var(--op-blue) !important; text-decoration: none !important; }
    /* Responsive */
    @media (max-width: 768px) { main.container { padding: 1.25rem 1rem !important; } main > div.f { flex-direction: column !important; align-items: flex-start !important; } section.live-status article.up, section.live-status article.degraded { grid-template-columns: 1fr !important; gap: 0.35rem !important; } section.live-status article.graph { background-size: 100% 24px !important; background-position: bottom center !important; } }
workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: 0 0 * * *
  responseTime: 0 */6 * * *
  staticSite: 0 1 * * *
  summary: 0 0 * * *
