owner: scaleupventures01
repo: offerpath-upptime

sites:
  # --- Public Pages ---
  - name: Homepage
    url: https://www.offerpath.co
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: About
    url: https://www.offerpath.co/about
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Calculator
    url: https://www.offerpath.co/calculator
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Cancellation
    url: https://www.offerpath.co/cancellation
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Church Board
    url: https://www.offerpath.co/church-board
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Enterprise
    url: https://www.offerpath.co/enterprise
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: FAQ
    url: https://www.offerpath.co/faq
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: For Designers
    url: https://www.offerpath.co/for-designers
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: For Engineers
    url: https://www.offerpath.co/for-engineers
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: For Product Managers
    url: https://www.offerpath.co/for-product-managers
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: For Visa Holders
    url: https://www.offerpath.co/for-visa-holders
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Glossary
    url: https://www.offerpath.co/glossary
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Insights
    url: https://www.offerpath.co/insights
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Jobs
    url: https://www.offerpath.co/jobs
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: LinkedIn Optimization
    url: https://www.offerpath.co/linkedin-optimization
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Login
    url: https://www.offerpath.co/login
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Partners
    url: https://www.offerpath.co/partners
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Pricing
    url: https://www.offerpath.co/pricing
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Privacy Policy
    url: https://www.offerpath.co/privacy
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Resources
    url: https://www.offerpath.co/resources
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Salary Discovery
    url: https://www.offerpath.co/salary-discovery
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: ScaleJobs
    url: https://www.offerpath.co/scalejobs
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Schedule
    url: https://www.offerpath.co/schedule
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Sign Up
    url: https://www.offerpath.co/signup
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Success Stories
    url: https://www.offerpath.co/success-stories
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: Terms of Service
    url: https://www.offerpath.co/terms
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: "Tool: ATS Checker"
    url: https://www.offerpath.co/tools/ats-checker
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: "Tool: Cover Letter"
    url: https://www.offerpath.co/tools/cover-letter
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: "Tool: LinkedIn Analyzer"
    url: https://www.offerpath.co/tools/linkedin-analyzer
    __dangerous__body_down_if_text_missing: "OfferPath"
  - name: "Tool: Salary Calculator"
    url: https://www.offerpath.co/tools/salary
    __dangerous__body_down_if_text_missing: "OfferPath"

  # --- API Endpoints (GET-capable) ---
  - name: Payment Verification
    url: https://www.offerpath.co/api/verify-checkout-session
    expectedStatusCodes:
      - 200
      - 400
  - name: Scheduling Service
    url: https://www.offerpath.co/api/scheduling/book-slot
    expectedStatusCodes:
      - 200
      - 400
      - 500
  - name: VA Availability
    url: https://www.offerpath.co/api/va/availability
    expectedStatusCodes:
      - 200
      - 400
      - 401
      - 500

  # --- API Endpoints (POST-only, monitored via GET -> 405) ---
  - name: Checkout Service
    url: https://www.offerpath.co/api/create-checkout-session
    expectedStatusCodes:
      - 405
  - name: Payment Webhooks
    url: https://www.offerpath.co/api/stripe-webhook
    expectedStatusCodes:
      - 405
  - name: Email Service
    url: https://www.offerpath.co/api/send-email
    expectedStatusCodes:
      - 405
  - name: SMS Service
    url: https://www.offerpath.co/api/send-sms
    expectedStatusCodes:
      - 405
  - name: Profile Notifications
    url: https://www.offerpath.co/api/notify-new-profile
    expectedStatusCodes:
      - 405
  - name: CRM Sync
    url: https://www.offerpath.co/api/sync-to-attio
    expectedStatusCodes:
      - 405
  - name: VA Magic Link
    url: https://www.offerpath.co/api/va/send-magic-link
    expectedStatusCodes:
      - 405
  - name: VA Token Verify
    url: https://www.offerpath.co/api/va/verify-token
    expectedStatusCodes:
      - 405

status-website:
  cname: status.offerpath.co
  logoUrl: https://www.offerpath.co/offerpath-logo.jpg
  name: OfferPath Status
  introTitle: "**OfferPath** System Status"
  introMessage: This page shows real-time uptime monitoring for [OfferPath](https://www.offerpath.co). Checks run every 5 minutes.
  theme: light
  navbar:
    - title: OfferPath
      href: https://www.offerpath.co
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: |
    :root {
      --op-blue: #2563eb;
      --op-green: #10b981;
      --op-green-light: #d1fae5;
      --op-red: #ef4444;
      --op-yellow: #f59e0b;
      --op-g50: #f9fafb;
      --op-g100: #f3f4f6;
      --op-g200: #e5e7eb;
      --op-g700: #374151;
      --op-g900: #111827;
    }
    body { background: var(--op-g50) !important; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif !important; }
    /* Nav */
    nav { background: white !important; border-bottom: 1px solid var(--op-g200) !important; box-shadow: 0 1px 3px rgba(0,0,0,0.06) !important; }
    nav .logo img { height: 28px !important; border-radius: 6px !important; }
    nav .logo div { font-weight: 700 !important; font-size: 1.1rem !important; color: var(--op-g900) !important; }
    nav ul a { color: var(--op-g700) !important; font-weight: 500 !important; }
    nav ul a:hover { color: var(--op-blue) !important; }
    /* Main container */
    main.container { max-width: 900px !important; margin: 0 auto !important; padding: 2rem 1.5rem !important; }
    /* Title */
    main h1 { font-size: 2rem !important; font-weight: 700 !important; color: var(--op-g900) !important; margin-bottom: 0.25rem !important; }
    main .lead { font-size: 1rem !important; color: var(--op-g700) !important; margin-bottom: 1.5rem !important; }
    main .lead a { color: var(--op-blue) !important; }
    /* Sections */
    main > section { background: white !important; border: 1px solid var(--op-g200) !important; border-radius: 12px !important; padding: 1.25rem 1.5rem !important; margin-bottom: 1.5rem !important; box-shadow: 0 1px 3px rgba(0,0,0,0.04) !important; }
    main > section h2 { font-size: 1.25rem !important; font-weight: 600 !important; color: var(--op-g900) !important; margin-bottom: 1rem !important; }
    /* Incidents */
    article.down { background: #fef2f2 !important; border: 1px solid #fecaca !important; border-radius: 8px !important; padding: 1rem !important; margin-bottom: 0.75rem !important; }
    article.down h4 { color: var(--op-red) !important; font-weight: 600 !important; }
    /* Time range selector */
    form label { display: inline-block !important; padding: 6px 14px !important; margin: 0 4px 8px 0 !important; background: var(--op-g100) !important; border: 1px solid var(--op-g200) !important; border-radius: 6px !important; font-size: 0.85rem !important; font-weight: 500 !important; color: var(--op-g700) !important; cursor: pointer !important; transition: all 0.15s !important; }
    form label:hover { background: var(--op-g200) !important; }
    form input[type="radio"] { display: none !important; }
    form input[type="radio"]:checked + label { background: var(--op-blue) !important; color: white !important; border-color: var(--op-blue) !important; }
    /* Live status heading */
    .live-status { background: transparent !important; border: none !important; box-shadow: none !important; padding: 0 !important; }
    /* Service cards */
    article.up, article.down.link, article.degraded { background: white !important; border: 1px solid var(--op-g200) !important; border-radius: 10px !important; padding: 1rem 1.25rem !important; margin-bottom: 0.75rem !important; box-shadow: 0 1px 2px rgba(0,0,0,0.04) !important; transition: all 0.15s !important; position: relative !important; }
    article.up:hover, article.degraded:hover { box-shadow: 0 4px 12px rgba(0,0,0,0.08) !important; border-color: #d1d5db !important; transform: translateY(-1px) !important; }
    /* Green dot before service name */
    article.up h4::before { content: "" !important; display: inline-block !important; width: 8px !important; height: 8px !important; background: var(--op-green) !important; border-radius: 50% !important; margin-right: 8px !important; box-shadow: 0 0 0 3px var(--op-green-light) !important; flex-shrink: 0 !important; }
    article.down h4::before { content: "" !important; display: inline-block !important; width: 8px !important; height: 8px !important; background: var(--op-red) !important; border-radius: 50% !important; margin-right: 8px !important; box-shadow: 0 0 0 3px #fecaca !important; flex-shrink: 0 !important; }
    /* Service name */
    article h4 { display: flex !important; align-items: center !important; font-size: 0.95rem !important; font-weight: 600 !important; margin-bottom: 4px !important; }
    article h4 .icon { width: 16px !important; height: 16px !important; border-radius: 3px !important; margin-right: 6px !important; }
    article h4 a { color: var(--op-g900) !important; text-decoration: none !important; }
    article h4 a:hover { color: var(--op-blue) !important; }
    /* Uptime/response stats */
    article.up > div, article.degraded > div { font-size: 0.8rem !important; color: var(--op-g700) !important; margin: 2px 0 !important; }
    article .data { font-weight: 600 !important; color: var(--op-g900) !important; }
    /* Graph background image */
    article.graph { background-size: 200px 60px !important; background-position: right center !important; background-repeat: no-repeat !important; }
    /* Footer */
    footer { margin-top: 3rem !important; padding: 1.5rem 0 !important; text-align: center !important; color: var(--op-g700) !important; font-size: 0.85rem !important; border-top: 1px solid var(--op-g200) !important; }
    footer a { color: var(--op-blue) !important; }
    /* Mobile */
    @media (max-width: 768px) { main.container { padding: 1rem !important; } article.graph { background-size: 120px 40px !important; } }

workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 0 * * *"
  responseTime: "0 */6 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
